export const missions = [
    {
        "id": "m1",
        "title": "Diagonal Intercept",
        "subtitle": "Corner deployment at maximum distance from the enemy",
        "category": "advanced",
        "categoryName": "Advanced",
        "type": "Diagonal",
        "deployment": "\n                    <p><strong>Player A:</strong> Top LEFT corner of the board. Triangular drop zone 10\" along the long edge and 10\" along the short edge.</p>\n                    <p><strong>Player B:</strong> Bottom RIGHT corner. Triangular zone 10\" x 10\".</p>\n                    <p><strong>Distance between zones:</strong> ~25 inches. Direct fire on Turning Point 1 is impossible.</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>4 Objectives:</strong> Placed along the central diagonal.</li>\n                        <li><strong>1 VP:</strong> For each active node at the end of the Turning Point (starting from TP 2).</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p><strong>Action - Hack Node (1 AP):</strong> An objective does not grant points just for being present. An operative must be within 1\" of the objective and spend 1 AP to hack it. After that, the objective is considered yours until the enemy recaptures it.</p>\n                ",
        "pace": "Due to the diagonal deployment, the first Turning Point is entirely spent bringing up forces and maneuvering behind cover."
    },
    {
        "id": "m2",
        "title": "Deep Breach",
        "subtitle": "Narrow front from the short edges of the board",
        "category": "advanced",
        "categoryName": "Advanced",
        "type": "Short Edge",
        "deployment": "\n                    <p><strong>Player A:</strong> Left short edge (22\"). A strip <strong>6 inches</strong> wide.</p>\n                    <p><strong>Player B:</strong> Right short edge (22\"). A strip <strong>6 inches</strong> wide.</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>1 VP:</strong> Control at least 1 objective on your half of the board.</li>\n                        <li><strong>1 VP:</strong> Control at least 1 objective on the enemy's half of the board.</li>\n                        <li><strong>2 VP:</strong> For controlling both objectives on the enemy's half of the board.</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p>The board is mentally divided in half. There is 1 objective in each quadrant. Points for objectives are awarded at the end of Turning Points 2, 3, and 4.</p>\n                ",
        "pace": "To secure maximum points, players must push forward into enemy territory through a narrow corridor."
    },
    {
        "id": "m3",
        "title": "Data Download",
        "subtitle": "Mission with delayed scoring",
        "category": "advanced",
        "categoryName": "Advanced",
        "type": "Frontal",
        "deployment": "\n                    <p><strong>Players A & B:</strong> Standard 6-inch strips along the long edges.</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>TP 1:</strong> Objectives DO NOT grant Victory Points!</li>\n                        <li><strong>TP 2, 3, 4:</strong> 1 VP for each hacked terminal.</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p><strong>Download Data (1 AP):</strong> An operative must spend 1 AP near the terminal. If the enemy drives you away from the terminal, they do not need to spend AP — the objective automatically becomes theirs.</p>\n                ",
        "pace": "The lack of scoring in the first Turning Point allows you to calmly establish a frontline and hack consoles before the main firefight begins."
    },
    {
        "id": "m4",
        "title": "High-Value Cargo",
        "subtitle": "Carrying heavy containers with debuffs",
        "category": "advanced",
        "categoryName": "Advanced",
        "type": "Frontal",
        "deployment": "\n                    <p><strong>Players A & B:</strong> Opposite long edges of the board (6 inches).</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>1 VP:</strong> For holding a crate at the end of the Turning Point.</li>\n                        <li><strong>3 VP:</strong> For delivering a crate to your drop zone and dropping it (<i>Drop</i> action for 1 AP).</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p><strong>Pick up Cargo (1 AP):</strong> An operative picks up 1 of the 3 crates in the center.</p>\n                    <p><strong>Weight Penalty:</strong> An operative carrying cargo suffers -2\" to Move and Charge, and <strong>CANNOT perform a Dash</strong>.</p>\n                ",
        "pace": "Escort mechanics. Whoever carries the crate becomes slow and an easy target. You will have to protect them with the bodies of allies."
    },
    {
        "id": "m5",
        "title": "Shifting Zone",
        "subtitle": "Dynamically changing active objectives",
        "category": "advanced",
        "categoryName": "Advanced",
        "type": "Frontal",
        "deployment": "\n                    <p><strong>Players A & B:</strong> Standard long zones (6 inches each).</p>\n                    <p>5 objectives: 2 closer to A, 1 in the Center, 2 closer to B.</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>TP 1:</strong> Only the 4 outer objectives are active (1 VP each).</li>\n                        <li><strong>TP 2:</strong> ONLY the Central objective is active (2 VP).</li>\n                        <li><strong>TP 3:</strong> Objectives IN THE ENEMY zone are active (2 VP each).</li>\n                        <li><strong>TP 4:</strong> ALL objectives are active (1 VP each).</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p>Capturing inactive objectives in the current Turning Point is pointless. You must constantly reposition to the required sector.</p>\n                ",
        "pace": "Camping in the base won't work. You must plan your maneuvers so that you are near the newly active objective by the next turn."
    },
    {
        "id": "m6",
        "title": "Bunker Assault",
        "subtitle": "Narrow zones and a massive obstacle in the center",
        "category": "basic",
        "categoryName": "Basic",
        "type": "Narrow Frontal",
        "deployment": "\n                    <p><strong>Players A & B:</strong> Narrow zones of only <strong>4 inches</strong> along the long edges.</p>\n                    <p>Prerequisite: A large building/bunker right in the center of the board blocking line of sight.</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>1 VP:</strong> For controlling objectives on the flanks outside the bunker.</li>\n                        <li><strong>2 VP:</strong> For controlling the central console inside the bunker.</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p>There is no direct line of sight from base to base. Capturing the central objective requires entering an enclosed space for close quarters combat.</p>\n                ",
        "pace": "The solid central terrain completely eliminates wiping out squads through shooting. Close combat is inevitable."
    },
    {
        "id": "m7",
        "title": "Line Control",
        "subtitle": "Classic capture and hold of 4 objectives",
        "category": "basic",
        "categoryName": "Basic",
        "type": "Frontal",
        "deployment": "\n                    <p><strong>Players A & B:</strong> Opposite long edges of the board (6 inches).</p>\n                    <p>4 objectives are placed in a diamond shape.</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>1 VP:</strong> Control 1 or more objectives at the end of the Turning Point.</li>\n                        <li><strong>1 VP:</strong> Control MORE objectives than your opponent.</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p>Control is determined by the number of models (sum of their APL) within 2\" of the marker.</p>\n                ",
        "pace": "A perfect balance of positional firefights. Great for learning the fundamentals of the game."
    },
    {
        "id": "m8",
        "title": "King of the Hill",
        "subtitle": "Uncompromising battle for the center",
        "category": "basic",
        "categoryName": "Basic",
        "type": "Frontal",
        "deployment": "\n                    <p><strong>Players A & B:</strong> Opposite edges of the board (6 inches).</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>2 VP:</strong> To the player controlling the single central objective at the end of the Turning Point.</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p>There is only one objective located exactly in the geometric center of the board. All shooting and charges will be directed there.</p>\n                ",
        "pace": "A maximally aggressive and fast format. Whoever makes the best use of cover around the objective will win."
    },
    {
        "id": "m9",
        "title": "Jamming Fields",
        "subtitle": "Objectives act as anti-sniper jamming generators",
        "category": "advanced",
        "categoryName": "Advanced",
        "type": "Checkered",
        "deployment": "\n                    <p><strong>Player A:</strong> Two 8x8 inch squares in the Top-Left and Bottom-Right corners of the board.</p>\n                    <p><strong>Player B:</strong> Two 8x8 inch squares in the Top-Right and Bottom-Left corners of the board.</p>\n                    <p>Your squads are initially split into two groups (Crossfire).</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>1 VP:</strong> For controlling each objective (Generator) at the end of the Turning Point.</li>\n                        <li><strong>1 VP (Bonus):</strong> If you control more Generators than the opponent.</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p><strong>Jamming Aura (Passive):</strong> Any operative within 2\" of ANY objective gains protection from ranged attacks. The enemy <strong>CANNOT</strong> shoot at this operative if the shooter is further than 6 inches away. Weapons with the <i>Blast</i> and <i>Indirect</i> rules ignore this.</p>\n                ",
        "pace": "Shooting across the board is completely disabled. Only those who aren't afraid to get up close (within 6 inches) or engage in melee will survive."
    },
    {
        "id": "m10",
        "title": "Asymmetric Sabotage",
        "subtitle": "One defends the center, the other attacks from the corners",
        "category": "advanced",
        "categoryName": "Advanced",
        "type": "Asymmetric",
        "deployment": "\n                    <p><strong>DEFENDER (Player A):</strong> A 10x10 inch square exactly in the center of the board.</p>\n                    <p><strong>ATTACKER (Player B):</strong> Two opposite corners of the board (8x8 inch triangles). The squad can be split into two parts.</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>DEFENDER:</strong> Gains 1 VP at the end of the Turning Point for each UNDESTROYED generator (there are 3).</li>\n                        <li><strong>ATTACKER:</strong> Instantly gains 3 VP for each destroyed generator.</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p><strong>Plant Bomb (1 AP):</strong> The Attacker can plant a charge on a generator (within 1\"). The charge explodes at the end of the NEXT Turning Point.</p>\n                    <p><strong>Defuse (1 AP):</strong> The Defender can spend AP to remove the charge before it detonates.</p>\n                ",
        "pace": "A very tense thriller. The Defender has to cover all directions, while the Attacker coordinates simultaneous assaults from two flanks."
    },
    {
        "id": "m11",
        "title": "Toxic Storm",
        "subtitle": "Shrinking zone and mortal wounds on the edges",
        "category": "advanced",
        "categoryName": "Advanced",
        "type": "Kill Zone",
        "deployment": "\n                    <p><strong>Players A & B:</strong> Standard long zones (6 inches each).</p>\n                    <p>4 objectives are grouped very close to the center of the board.</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>1 VP:</strong> For controlling any objective.</li>\n                        <li><strong>1 VP:</strong> If you control more objectives than your opponent.</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p><strong>Shrinking Zone:</strong> At the end of Turning Point 2, any operative within 3\" of ANY edge of the board suffers D3 mortal wounds. During Turning Points 3 and 4, this kill zone expands to 6\" from the edges.</p>\n                ",
        "pace": "Classic \"Battle Royale\" mechanics. By the third Turning Point, all surviving operatives will be forced to huddle in the center of the board at melee range."
    },
    {
        "id": "m12",
        "title": "Shifting Front",
        "subtitle": "Random activation of objectives each turn",
        "category": "advanced",
        "categoryName": "Advanced",
        "type": "Diagonal",
        "deployment": "\n                    <p><strong>Players A & B:</strong> Diagonal deployment (10x10 inch corners).</p>\n                    <p><strong>6 numbered objectives</strong> (from 1 to 6) are scattered across the board.</p>\n                ",
        "scoring": "\n                    <ul class=\"list-disc pl-5 space-y-1\">\n                        <li><strong>2 VP:</strong> For controlling an objective active in this Turning Point.</li>\n                    </ul>\n                ",
        "mechanics": "\n                    <p><strong>Wandering Signal:</strong> At the start of EACH Turning Point, roll a D6 TWICE. The resulting numbers indicate the only two objectives that will yield points this round. The other 4 objectives become inactive dummies until the next roll.</p>\n                ",
        "pace": "Utter chaos. It is impossible to sit in a static defense, as the required objective might activate on the other side of the board. Requires maximum squad flexibility."
    }
];
